services:

  pqr-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pqr-management
    ports:
      - ${APP_DOCKER_PORTS}
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

