spring.application.name=pqr
spring.profiles.active=${SPRING_PROFILES_ACTIVE:test}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
pqr.book.order.threshold = ${PQR_BOOK_ORDER_THRESHOLD}
services.book.order.url = ${SERVICES_BOOK_ORDER_URL}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=pqr-management