# Set root to INFO to avoid library noise
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

# Let Hibernate create/update tables for us
spring.jpa.hibernate.ddl-auto=update
# Show us the SQL it's running so we can learn
spring.jpa.show-sql=true